#!/bin/sh

document=$1

pandoc $document -o document.tex
node cleanup.js

echo "============ DEBUG DOCUMENT ============"
cat document.md
echo "============ DEBUG DOCUMENT ============"

latexmk -r latexmkrc -pdfxe document.tex

