#!/bin/sh

export GIT_WORK_TREE=$(pwd)
export GIT_DIR=${GIT_WORK_TREE}/.git

git config user.name "GitHub Actions Bot"
git config user.email "<>"
git config pull.rebase false

git add -A
git commit -m "auto generated commit by github actions"

git status
cat .git/HEAD

git fetch
git checkout master
git pull
git merge markdown

git push -u origin master
