#!/bin/sh

export GIT_WORK_TREE=$(pwd)
export GIT_DIR=${GIT_WORK_TREE}/.git

git config user.name "GitHub Actions Bot"
git config user.email "<>"

git add -A
git commit -m "auto generated commit by github actions"
git push origin master
