name: Compile markdown to latex pdf

on:
  push:
    branches: [ markdown ]

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
    - name: apt-get update
      run: sudo apt-get update
    - name: packages
      run: sudo apt-get install latexmk texlive-xetex pandoc tex-gyre nodejs
    - name: build document
      run: ./build document.md
    - name: commit changes
      run: ./commit

